spring.application.name=Buyfurn

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
springdoc.swagger-ui.path=/swagger-ui.html

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.jpa.open-in-view=false

spring.profiles.active=dev